version: '3'

services:
  db:
    image: mysql:8.0
    env_file:
      - ./db.env
    ports:
      - '3306:3306'
    volumes:
      - ./mysql-init-scripts:/docker-entrypoint-initdb.d
  redis-db:
    image: redis:alpine
    ports:
      - '6379:6379'
  api:
    image: config_center:local
    env_file: ./.env
    depends_on:
      - db
    ports:
      - '8080:8080'
